// Available student statuses in the system
export type StudentStatus = "active" | "paused" | "completed" | "dropped";

// Main student entity used across the app
export type Student = {
  _id?: string;
  firstName: string;
  lastName: string;
  age: number;
  email: string;
  course: string;
  status: StudentStatus;
  dateOfRegistration: string;
  createdAt?: string;
  updatedAt?: string;
};

// Payload used when creating or updating a student
// `_id` is excluded because it is generated by the backend
export type StudentPayload = Omit<Student, "_id">;

// Reducer state shape used to manage student data in one place.
export type StudentState = {
  students: Student[];
  loading: boolean;
  editingStudent: Student | null;
};

// Reducer actions used with dispatch to update student state.
export type StudentAction =
  | { type: "SET_LOADING"; payload: boolean }
  | { type: "SET_STUDENTS"; payload: Student[] }
  | { type: "ADD_STUDENT"; payload: Student }
  | { type: "UPDATE_STUDENT"; payload: Student }
  | { type: "DELETE_STUDENT"; payload: string }
  | { type: "SET_EDITING_STUDENT"; payload: Student | null };

// Context API contract for accessing student state and actions globally
export type StudentContextValue = {
  students: Student[];
  loading: boolean;
  editingStudent: Student | null;
  fetchStudents: () => Promise<void>;
  addStudent: (student: StudentPayload) => Promise<void>;
  updateStudent: (id: string, student: StudentPayload) => Promise<void>;
  deleteStudent: (id: string) => Promise<void>;
  setEditingStudent: (student: Student | null) => void;
};

// Form state shape
// `age` is stored as string because input fields return string values
export type FormData = {
  firstName: string;
  lastName: string;
  age: string;
  email: string;
  course: string;
  status: StudentStatus;
  dateOfRegistration: string;
};

// Generic dropdown option type for select inputs
export type Option = {
  label: string;
  value: string;
};

// Props for custom dropdown component
export type DropdownMenuProps = {
  value: string;
  options: Option[];
  onChange: (value: string) => void;
};

// Props for student modal form component
export type StudentFormProps = {
  isOpen: boolean;
  onClose: () => void;
};

// Props for students list/table component
export type StudentsTableProps = {
  onAdd: () => void;
};